// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contacts/:contactId": {
    params: {
      "contactId": string;
    };
  };
  "/todo": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/contacts/:contactId" | "/todo";
  };
  "./rr-main.jsx": {
    id: "rr-main";
    page: "/" | "/contacts/:contactId";
  };
  "./router/address-book/AddressBook.jsx": {
    id: "router/address-book/AddressBook";
    page: "/";
  };
  "./router/address-book/routes/ContactDetailPage.jsx": {
    id: "router/address-book/routes/ContactDetailPage";
    page: "/contacts/:contactId";
  };
  "./react-official/use-effects/not-need/challenge-one/Todo.jsx": {
    id: "react-official/use-effects/not-need/challenge-one/Todo";
    page: "/todo";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "rr-main": typeof import("./src/./rr-main.jsx");
  "router/address-book/AddressBook": typeof import("./src/./router/address-book/AddressBook.jsx");
  "router/address-book/routes/ContactDetailPage": typeof import("./src/./router/address-book/routes/ContactDetailPage.jsx");
  "react-official/use-effects/not-need/challenge-one/Todo": typeof import("./src/./react-official/use-effects/not-need/challenge-one/Todo.jsx");
};