// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/";
  };
  "./rr-main.jsx": {
    id: "rr-main";
    page: "/";
  };
  "./router/address-book/AddressBook.jsx": {
    id: "router/address-book/AddressBook";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "rr-main": typeof import("./src/./rr-main.jsx");
  "router/address-book/AddressBook": typeof import("./src/./router/address-book/AddressBook.jsx");
};